[package]
name = "secret_santa"
version = "0.1.0"
authors = ["QVSorrow <olesnk21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"